version: "2.1"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    restart: on-failure
    ports:
    - 32181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 100

  job-dispatcher-1:
    image: totango/job-dispatcher
    environment:
      _JAVA_OPTIONS: -Xmx256m
      APP_ARGS: "zookeeper:2181"

  job-dispatcher-2:
    image: totango/job-dispatcher
    environment:
      _JAVA_OPTIONS: -Xmx256m
      APP_ARGS: "zookeeper:2181"

  job-dispatcher-3:
    image: totango/job-dispatcher
    environment:
      _JAVA_OPTIONS: -Xmx256m
      APP_ARGS: "zookeeper:2181"

  job-dispatcher-4:
    image: totango/job-dispatcher
    environment:
      _JAVA_OPTIONS: -Xmx256m
      APP_ARGS: "zookeeper:2181"
